### ISSUE TITLE
Implement some kind of decorator pattern for some functions similar to hdk-rust macros

### ISSUE THREAD

**Issue by Connoropolous** [holochain/hdk-assemblyscript#2]

**Comment by MaxGraey** [comment]
You could do some code generation for decorators by using `--transform` arg via cli or `afterParse` method via code. See [for details](https://github.com/AssemblyScript/assemblyscript/blob/0d64c9661a60446164c38bf414613ca8ac9cf88e/cli/transform.d.ts)

The same approach using in [`ewasm`](https://github.com/etherts/ewasm-as/blob/master/assembly/src/transform.js)

**Comment by Connoropolous** [comment]
I'll look into those, thanks!!

**Comment by Connoropolous** [comment]
@MaxGraey What is the reason for the fork of assemblyscript? 

https://github.com/AssemblyScript/assemblyscript/compare/master...lrettig:ewasm

Just to get a couple extra exports that you use here?
https://github.com/etherts/ewasm-as/blob/master/assembly/src/transform.js#L14-L21

**Comment by MaxGraey** [comment]
Yeah, only for extra exports, so if you need making some extra public entities you could also fork AS and making PR to main repo after you stabilize things which you required

**Comment by Connoropolous** [comment]
Cool, yes. Just got a PR in this repo open with exactly the approach you made mention of. I don't want to make any assumptions about your available time @MaxGraey, but it could be very valuable to have an experienced set of eyes give it a quick look over. Very appreciative of your comments so far.

**Comment by MaxGraey** [comment]
Sure, I will keep my eyes on your PR
